/** 智能体可操作的站点工具目录（服务端系统提示 + 客户端预填字段约定） */
export const AGENT_TOOLS = [
  {
    id: "video-extract",
    title: "视频链接提取",
    href: "/tools/video-extract",
    description: "解析抖音、B站、YouTube、微信视频号等链接并下载",
    fields: { url: "视频页面链接" },
  },
  {
    id: "media-search",
    title: "影视搜索",
    href: "/tools/media-search",
    description: "输入片名，聚合影视信息与可复制的资源链接包",
    fields: { keyword: "片名或关键词" },
  },
  {
    id: "media-download",
    title: "影视资源下载",
    href: "/tools/media-download",
    description: "按片名检索网盘资源链接，多平台一键复制",
    fields: { keyword: "片名或关键词" },
  },
  {
    id: "music-convert",
    title: "音乐工坊",
    href: "/tools/music-convert",
    description: "解锁主流平台加密音乐，批量转换为 MP3、FLAC 等格式",
    fields: { format: "MP3|FLAC|WAV|AAC|OGG|M4A" },
  },
  {
    id: "image-studio",
    title: "图像工坊",
    href: "/tools/image-studio",
    description: "图片压缩、清晰增强、智能抠图、人像美化、AI 修图与文生图",
    fields: { mode: "compress|sharpen|cutout|beautify|edit|generate", prompt: "生图或修图描述" },
  },
  {
    id: "ai-search",
    title: "AI 全网搜索",
    href: "/tools/ai-search",
    description: "全网检索并由 AI 生成带引用的答案",
    fields: { query: "搜索问题或关键词" },
  },
  {
    id: "app-builder",
    title: "一键做 App",
    href: "/tools/app-builder",
    description: "生成单页 Web 应用；支持快捷指令配套（URL API 调用）",
    fields: {
      description: "应用需求描述",
      appType: "tool|shortcuts|api|landing|dashboard|game|form",
      appName: "应用名称",
    },
  },
  {
    id: "ai-writer",
    title: "AI 写作助手",
    href: "/tools/ai-writer",
    description: "多模式写作：文章、改写、润色、摘要、社媒文案等",
    fields: { mode: "article|rewrite|polish|expand|summarize|social|email|translate", input: "文本或主题" },
  },
  {
    id: "ai-workflow",
    title: "AI 工作流",
    href: "/tools/ai-workflow",
    description: "多步 AI 流水线：内容创作、社媒包、视频脚本",
    fields: { workflowId: "content-pipeline|social-pack|script-pipeline", input: "主题或素材" },
  },
  {
    id: "hot-trends",
    title: "热点中心",
    href: "/tools/hot-trends",
    description: "抖音、小红书实时热点",
    fields: { platform: "douyin|xiaohongshu" },
  },
  {
    id: "social-publish",
    title: "社媒一键分发",
    href: "/tools/social-publish",
    description: "一条视频/文案分发到抖音、视频号、小红书、B站、快手",
    fields: {
      title: "标题",
      description: "正文文案",
      tags: "话题标签",
      platforms: "douyin,weixin-channels,xiaohongshu 等逗号分隔",
    },
  },
  {
    id: "spider-builder",
    title: "小蜘蛛爬虫",
    href: "/tools/spider-builder",
    description: "可视化网页数据抓取",
    fields: { url: "要抓取的网页地址" },
  },
  {
    id: "doc-convert",
    title: "文档转换",
    href: "/tools/doc-convert",
    description: "PDF/Word 互转、PDF 转图片、图片转 PDF",
    fields: { mode: "pdf-to-word|word-to-pdf|pdf-to-images|images-to-pdf" },
  },
  {
    id: "subtitle-workshop",
    title: "字幕工坊",
    href: "/tools/subtitle-workshop",
    description: "语音转字幕、提取内嵌字幕",
    fields: { tab: "transcribe|extract|edit" },
  },
  {
    id: "gif-maker",
    title: "GIF 动图",
    href: "/tools/gif-maker",
    description: "视频片段转 GIF",
    fields: { start: "起始秒", duration: "时长秒", fps: "帧率", width: "宽度px" },
  },
  {
    id: "ai-video-edit",
    title: "AI 视频剪辑",
    href: "/tools/ai-video-edit",
    description: "智能剪辑或 AI 剪口播：文稿匹配素材并合成人声",
    fields: {
      mode: "edit|voiceover",
      instruction: "剪辑/匹配要求",
      script: "口播文稿（剪口播模式）",
    },
  },
  {
    id: "text-toolbox",
    title: "文本工具箱",
    href: "/tools/text-toolbox",
    description: "字数统计、JSON、Markdown",
    fields: { tab: "stats|dedupe|json|markdown", input: "待处理文本" },
  },
  {
    id: "memory",
    title: "记忆库",
    href: "/tools/memory",
    description: "保存用户偏好与重要信息，供 AI 对话参考",
    fields: { content: "记忆内容" },
  },
];

export const AGENT_CATEGORIES = ["全部", "AI", "图像", "视频", "音频", "文档", "运营", "影视", "开发"];
